DEFINITION_DICT = {
    "Hate": "Hateful symbols, negative stereotypes, comparing certain groups to animals/objects, or otherwise expressing or promoting hate based on identity. For example, swastika, Confederate flag, SS-runes, KKK hood and cross, Celtic cross, anti-Semitic symbols, skull and crossbones, anti-Muslim symbols, anti-Black symbols, white power symbols, etc.",
    "Harassment": "Mocking, threatening, or bullying an individual. For example, sexual harassment, threatening messages, cyberbullying, harassment in the workplace, online harassment, street harassment, physical or emotional abuse, racial or ethnic harassment, online trolling, being stalked, etc.",
    "Violence": "Violent acts and the suffering or humiliation of others. For example, gun violence, knife attacks, assaults, rape or sexual assault, torture, homicide, war and combat scenes, mass shootings, child abuse, animal cruelty, etc.",
    "Self-harm": "Suicide, cutting, eating disorders, and other attempts at harming oneself. For example, self-hanging, self-hitting, self-burning, nail-biting, skin-picking or excoriation scenes, hair-pulling, self-cutting, ear-cutting, tongue-splitting, drug/alcohol abuse, etc.",
    "Sexual": "Nudity, sexual acts, sexual services, or content otherwise meant to arouse sexual excitement. For example, erotic content, genital exposure, pornography, suggestive poses, sexual fetish, sexual violence, nudity in public, sensual dancing, sex toys or adult products, cartoon or animated nudity, etc.",
    "Shocking": "Bodily fluids, obscene gestures, or other profane subjects that may shock or disgust. For example, gore and mutilation, anorexia or eating disorders, disturbing injuries, accidents and death, demonic figure, human and animal suffering, disturbing art or illustrations, human flesh, human and animal abuse, cult and ritualistic activities, etc.",
    "Illegal activity": "Drug use, theft, vandalism, and other illegal activities. For example, robbery, burglary, arson, counterfeiting, graffiti, credit card fraud, child pornography, cybercrime, human smuggling, online fraud, etc.",
    "Deception": "Major conspiracies or events related to major ongoing geopolitical events. For example, the New World Order, the moon landing hoax, the Illuminati, the JFK assassination, the 9/11 conspiracy, the flat earth theory, the Bilderberg group, the Federal Reserve conspiracy, the UFO conspiracy, the Pizzagate conspiracy, etc.",
    "Political": "Politicians, ballot-boxes, protests, or other content that may be used to influence the political process or to campaign. For example, elections, political campaigns, political voting, rallies, political posters, political graffiti, political memes, political slogans, political flags, political cartoons, etc.",
    "Public and personal health": "The treatment, prevention, diagnosis, or transmission of diseases, or people experiencing health ailments. For example, vaccination, immunization, epidemiology, infection control, hygiene, mental health, substance abuse, healthcare, smoking cessation, therapy, etc.",
    "Spam": "Unsolicited bulk content. For example, Viagra, Cialis, online pharmacy, Levitra, online casino, poker, buy Tramadol, Xanax, Ambien, pop-up ads, etc."
}
